stages:
  - test

.py:
  image: python:3
  stage: test
  script:
    - python runner.py data/${CI_JOB_NAME:2} "python src/${CI_JOB_NAME:2}/_.py"

py2015:
  extends: .py

py2016:
  extends: .py

py2019:
  extends: .py

py2020:
  extends: .py

py2021:
  extends: .py
