py-runner:
  image: python:3
  script:
    - python runner.py data/$YEAR "python src/$YEAR/_.py"
  parallel:
    matrix:
      - YEAR: [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]
  rules:
    - changes:
      - src/$YEAR/*
      - data/$YEAR/*
    - when: manual
      allow_failure: false
